version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./keys:/app/keys
    depends_on:
      - mysql
    networks:
      - blockchain_network
    restart: always

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: blockchain
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    networks:
      - blockchain_network
    restart: always

networks:
  blockchain_network:
    driver: bridge